### PR TITLE
JupyterLab4 compatibility draft: Dependency updates and typescript code changes

### PR DESCRIPTION
**Pull request by ericsnekbytes**
This PR serves as a starting point for updating the Variable Inspector extension for compatibility with JupyterLab 4. Basic summary:

- Update extension logic in typescript
- Bump dependencies on JupyterLab and its core plugins

### CODE REVIEW

**Comment by lckr** [comment]
Hey, thanks for this MR! I will try to get the CI here to work again before merging.
Additionally I'm thinking to wait for the official 4.0 release of Jupyterlab before releasing a new version of the extension. But on the other hand the dependencies probably won't change too much and we could already release with a JLab pre-release as target. What are your thoughts on this?

**Comment by ericsnekbytes** [comment]
Hey! Sorry for the delay, I would also recommend waiting for the Lab 4 official release (so both the core lab dependencies and the the dependency on lab itself would need to be modified to support the new released version numbers + any versions in that release series in that case).

**Comment by lckr** [comment]
Thanks @ericsnekbytes, I'm currently working on the update that will also change a few other things instead of just the dependency. I hope to get it done within the next week.

**Comment by lckr** [comment]
But if you were to update this MR with the current package versions we could also merge it before I finish the other changes :)

**Pull request merged**
